name: PR

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    # needs: msw
    # if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install node_modules
        run: |
          npm ci

      - name: Run linting
        continue-on-error: true # next step fails in case of errors
        run: npm run lint:ci
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        if: ${{ always() && github.actor != 'dependabot[bot]' }} # dependabot doesn't have permissions
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'
          only-pr-files: false
          fail-on-warning: false
      # - name: Check if proxies files has correct structure
      #   uses: actions/github-script@v7
