name: create

on:
  workflow_dispatch:

permissions: write-all
  # contents: write
  # pull-requests: write

env:
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub
  GIT_COMMITTER_EMAIL: actions@github.com
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  #BRANCH_NAME: msw-update-${{ github.run_id }}
##
jobs:
  update_msw_worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install node_modules
        run: |
          npm ci

      - name: Authenticate with PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo $PAT_TOKEN | gh auth login --with-token

      - name: Regenerate mockServiceWorker.js
        run: |
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b MSW-1

          npm i msw@latest
          
          npx msw init public/ --save

      - name: Check for changes in mockServiceWorker.js
        run: |
          if [[ $(git status --porcelain) ]]; then
            git status --porcelain

            git add package-lock.json
            git add package.json
            git add public/mockServiceWorker.js
            git commit -m "ROM - blabla"
          else
            echo "No changes in mockServiceWorker.js"
          fi

      - name: Push new branch
        run: |
          git push origin MSW-1 || git push --set-upstream origin MSW-1

      - name: Create new pull request
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base master --head MSW-1 --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
          # gh pr create --title "My test title" --body "This PR updates the translations from OneSky" --head MSW-1 --base master
          ###        
          # curl -X POST \
          #   -H "Authorization: token $GITHUB_TOKEN" \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   -d '{"title":"Automated PR creation","head":"MSW-1","base":"main"}' \
          #   https://api.github.com/repos/${{ github.repository }}/pulls

          #gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
          
              